### ISSUE TITLE
Hello, Dr. Barth. i'm the questioner on latest question. i have a question about the sentence about paper.

### ISSUE THREAD

**Issue by jsihunh** [gher-ulg/DINCAE#4]
I'm sorry to ask about your paper that doesn't relate to DINCAE.
Is there any reason to deduct the time average without cross-validation? As I understand this sentence,  cross-validation data will be considered independent data from the total length of the study period. Am I right? or Does any reasons for conduct it?

![image](https://user-images.githubusercontent.com/62535420/100751491-b7b07e00-342a-11eb-8d87-7f87ada5da86.png)

Kind Regards,
Sihun Jung

**Comment by Alexander-Barth** [comment]
The reason for this is that you do not want to validation data to influence the output of the neural network during training. If the mean is computed over  all data, then the mean uses the validation data and the validation data indirectly influences the result during training. I would not expect that the influence is very large but nevertheless it is better to keep the training independent of the validation data.

**Comment by jsihunh** [comment]
Thank you for your answer.
