### ISSUE TITLE
create input file for multi MODIS dataset

### ISSUE THREAD

**Issue by wulan87** [gher-ulg/DINCAE#6]
This is not bug question, rather a newbie question.

I don't understand **what to do** next **after create** _create_input_file.jl_ and, how it work with multifiles MODIS overthere? 
is that correlate with append mode like in the NCDatasets.jl does? to aggregate sst variables?

Thank you

**Comment by Alexander-Barth** [comment]
In this particular case, I used the Linux tool `ncks` from the `nco` package to concatenate the individual files to a single NetCDF files.

Here are some documentations that might be helpful for you:
https://forum.marine.copernicus.eu/discussion/205/how-to-mergeconcatenate-cmems-netcdf-files-tips/p1
https://disc.gsfc.nasa.gov/information/howto?title=How%20to%20Concatenate%20the%20Time%20Dimension%20of%20netCDF%20Files%20with%20NCO

**Comment by wulan87** [comment]
Thank you
